# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name:    RESEARCH&nbsp;&nbsp;&nbsp;&nbsp;
    url: 'research'
    weight: 20
  - name:    TEACHING&nbsp;&nbsp;&nbsp;&nbsp;       
    url: 'teaching'
    weight: 30
  - name:    COLIN DOYLE&nbsp;&nbsp;&nbsp;&nbsp;      
    url: '/'
    weight: 10



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/Doyle_Colin_CV.pdf
    weight: 100
